# GraphSAGE configuration for Cora dataset
model_type: GraphSage
dataset: Cora
hidden_dim: 64
num_layers: 2
epochs: 500
dropout: 0.5
batch_size: 32
lr: 0.01
weight_decay: 0.005
opt: adam
opt_scheduler: none
opt_restart: 0
eval_every: 10
